imports:
    - { resource: parameters.yml }
    - { resource: "@PimxFrontendBundle/Resources/config/parameters.yml" }
    - { resource: security.yml }

framework:
    #esi:             ~
    translator:      { fallback: %locale% }
    secret:          %secret%
    router:
        resource: "%kernel.root_dir%/config/routing.yml"
        strict_requirements: ~
    form:            ~
    csrf_protection: ~
    validation:      { enable_annotations: true }
    templating:
        engines: ['twig']
        #assets_version: SomeVersionScheme
    default_locale:  "%locale%"
    trusted_proxies: ~
    session:         ~
    fragments:       ~
    http_method_override: true

# Twig Configuration
twig:
    debug:            %kernel.debug%
    strict_variables: %kernel.debug%
    form:
        resources: ['::form_layout.html.twig']

# Assetic Configuration
assetic:
    debug:          %kernel.debug%
    use_controller: false
    bundles:        [ ]
    #java: /usr/bin/java
    filters:
        cssrewrite: ~
        #closure:
        #    jar: %kernel.root_dir%/Resources/java/compiler.jar
        #yui_css:
        #    jar: %kernel.root_dir%/Resources/java/yuicompressor-2.4.7.jar

# Doctrine Configuration
doctrine:
    dbal:
      default_connection:       default
      connections:
        default:
          driver:   %database_driver%
          host:     %database_host%
          port:     %database_port%
          dbname:   %database_name%
          charset:  UTF8
          wrapper_class: 'Pimx\DoctrineBundle\Connection\ConnectionWrapper'
          

    orm:
      default_entity_manager:   default
      auto_generate_proxy_classes: %kernel.debug%
      entity_managers:
        default:
            connection:       default
            auto_mapping:     true

# Swiftmailer Configuration
swiftmailer:
    transport: %mailer_transport%
    host:      %mailer_host%
    username:  %mailer_user%
    password:  %mailer_password%
    spool:     { type: memory }

# Services
services:
    pimx_frontend.listener.login:
        class: Pimx\FrontendBundle\EventListener\SecurityListener
        arguments: ["@security.context", "@doctrine", "@service_container"]
        calls:
            - [setRequest, ['@?request=']]
        tags:
            - { name: kernel.event_listener, event: security.interactive_login, method: onSecurityInteractiveLogin }
    pimx.security.user_provider:
        class:  Pimx\ModelBundle\Security\PimxUserProvider
        arguments: ["%kernel.root_dir%/Resources/users.yml"]
        
    wsse.security.authentication.provider:
        class:  Pimx\ApiBundle\Security\Authentication\Provider\WsseProvider
        arguments: ["", "%kernel.cache_dir%/security/nonces"]
    wsse.security.authentication.listener:
        class:  Pimx\ApiBundle\Security\Firewall\WsseListener
        arguments: ["@security.context", "@security.authentication.manager", "@service_container"]

#Sensio
sensio_framework_extra:
    view:
        annotations: false
        
#JMS Serializer
jms_serializer:
    handlers:
        datetime:
            default_format:       'Y-m-d\TH:i:s'
    metadata:
        auto_detection: true
        directories:
            pimx:
                namespace_prefix: Pimx\ModelBundle\Entity
                path: "@PimxApiBundle/Resources/config/serializer"
                
#FOS Rest
fos_rest:
    disable_csrf_role: ROLE_API
    routing_loader:
        default_format: json
    body_listener:
        decoders:
            json: fos_rest.decoder.jsontoform
    view:
        view_response_listener: true
#        jsonp_handler: ~
        formats:
            json: true
    format_listener: true
    
#Nelmio CORS
nelmio_cors:
    defaults:
        allow_credentials: false
        allow_origin: []
        allow_headers: []
        allow_methods: []
        expose_headers: []
        max_age: 0
        hosts: []
        origin_regex: false
    paths:
        '^/api/':
            allow_origin: ['*']
            allow_headers: ['*']
            allow_methods: ['POST', 'PUT', 'GET', 'DELETE', 'OPTIONS']
            max_age: 3600
        '^/':
            origin_regex: true
            allow_origin: ['^http://localhost:[0-9]+']
            allow_headers: ['X-Custom-Auth']
            allow_methods: ['POST', 'PUT', 'GET', 'DELETE']
            max_age: 3600
            hosts: ['^api\.']
