_account:
    pattern:  /accounts
    defaults: { _controller: PimxFrontendBundle:Account:index }
_account_new:
    pattern:  /accounts/new
    defaults: { _controller: PimxFrontendBundle:Account:new }
_account_edit:
    pattern:  /accounts/{item_id}/edit
    defaults: { _controller: PimxFrontendBundle:Account:edit }
    
_movement:
    pattern:  /movements
    defaults: { _controller: PimxFrontendBundle:Movement:index }
_movement_new:
    pattern:  /movements/new
    defaults: { _controller: PimxFrontendBundle:Movement:new }
_movement_edit:
    pattern:  /movements/{item_id}/edit
    defaults: { _controller: PimxFrontendBundle:Movement:edit }
_movement_delete:
    pattern:  /movements/{item_id}/delete
    defaults: { _controller: PimxFrontendBundle:Movement:delete }
    
_currency:
    pattern:  /currencies/
    defaults: { _controller: PimxFrontendBundle:Currency:index }
    
_label:
    pattern:  /labels/
    defaults: { _controller: PimxFrontendBundle:Label:index }
    
_report_fin_monthbalance:
    pattern:  /report/finance/monthbalance/
    defaults: { _controller: PimxFrontendBundle:Report:monthbalance }
_report_fin_accountbalance:
    pattern:  /report/finance/accountbalance/
    defaults: { _controller: PimxFrontendBundle:Report:accountbalance }
_report_fin_groupbalance:
    pattern:  /report/finance/bygroups/
    defaults: { _controller: PimxFrontendBundle:Report:groupbalance }
    
_note:
    pattern:  /notes/
    defaults: { _controller: PimxFrontendBundle:Note:index }
_note_new:
    pattern:  /notes/new/
    defaults: { _controller: PimxFrontendBundle:Note:new }
_note_edit:
    pattern:  /notes/{item_id}/edit
    defaults: { _controller: PimxFrontendBundle:Note:edit }
    
database_backup:
    pattern:  /database/backup
    defaults: { _controller: PimxFrontendBundle:Database:backup }
    
    
login:
    pattern:   /login
    defaults:  { _controller: PimxFrontendBundle:Security:login }
login_check:
    pattern:   /login_check
logout:
    path:      /logout
    
_home:
    pattern:  /
    defaults: { _controller: PimxFrontendBundle:General:home }
