_account:
    pattern:  /account/
    defaults: { _controller: PimxFrontendBundle:Account:index }
_account_new:
    pattern:  /account/new/
    defaults: { _controller: PimxFrontendBundle:Account:new }
_account_edit:
    pattern:  /account/edit/{item_id}
    defaults: { _controller: PimxFrontendBundle:Account:edit }
    
_movement:
    pattern:  /movement/
    defaults: { _controller: PimxFrontendBundle:Movement:index }
_movement_new:
    pattern:  /movement/new/
    defaults: { _controller: PimxFrontendBundle:Movement:new }
_movement_edit:
    pattern:  /movement/edit/{item_id}
    defaults: { _controller: PimxFrontendBundle:Movement:edit }
_movement_delete:
    pattern:  /movement/delete/{item_id}
    defaults: { _controller: PimxFrontendBundle:Movement:delete }
    
_currency:
    pattern:  /currency/
    defaults: { _controller: PimxFrontendBundle:Currency:index }
    
_label:
    pattern:  /label/
    defaults: { _controller: PimxFrontendBundle:Label:index }
    
_report_fin_monthbalance:
    pattern:  /report/finance/monthbalance/
    defaults: { _controller: PimxFrontendBundle:Report:monthbalance }
_report_fin_accountbalance:
    pattern:  /report/finance/accountbalance/
    defaults: { _controller: PimxFrontendBundle:Report:accountbalance }
_report_fin_groupbalance:
    pattern:  /report/finance/bygroups/
    defaults: { _controller: PimxFrontendBundle:Report:groupbalance }
    
_note:
    pattern:  /note/
    defaults: { _controller: PimxFrontendBundle:Note:index }
_note_new:
    pattern:  /note/new/
    defaults: { _controller: PimxFrontendBundle:Note:new }
_note_edit:
    pattern:  /note/edit/{item_id}
    defaults: { _controller: PimxFrontendBundle:Note:edit }
    
database_backup:
    pattern:  /database/backup
    defaults: { _controller: PimxFrontendBundle:Database:backup }
    
    
login:
    pattern:   /login
    defaults:  { _controller: PimxFrontendBundle:Security:login }
login_check:
    pattern:   /login_check
logout:
    path:      /logout
    
_home:
    pattern:  /
    defaults: { _controller: PimxFrontendBundle:General:home }
