Pimx\ModelBundle\Entity\MovementAccount:
    type: entity
    table: cuentasxmovim
    id:
        id:
            type: integer
            column: cxm_ID
            generator:
              strategy: AUTO
    fields:
        sign:
            type: integer
            column: cxm_Sentido
        amount:
            type: decimal
            column: cxm_Importe
    manyToOne:
        movement:
            targetEntity: Movement
            joinColumn:
                name: cxmmov_ID
                referencedColumnName: mov_ID
        account:
            targetEntity: Account
            joinColumn:
                name: cxmcta_cod
                referencedColumnName: cta_Cod