Pimx\ModelBundle\Entity\MovementAccount:
    type: entity
    table: cuentasxmovim
    id:
        movement:
            associationKey: true
        account:
            associationKey: true
        sign:
            type: integer
            column: cxm_Sentido
    fields:
        amount:
            type: decimal
            column: cxm_Importe
    manyToOne:
        movement:
            targetEntity: Movement
            inversedBy: appliedAccounts
            joinColumn:
                name: cxmmov_ID
                referencedColumnName: mov_ID
        account:
            targetEntity: Account
            joinColumn:
                name: cxmcta_cod
                referencedColumnName: cta_Cod