Pimx\ModelBundle\Entity\Movement:
    exclusion_policy: ALL
    properties:
        id:
            expose: true
        date:
            expose: true
        name:
            expose: true
        type:
            expose: true
        group:
            expose: true